# Generated by Django 5.2.4 on 2025-07-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image, file, or media', null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(help_text='Room where this message was sent', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(help_text='Users who are members of this chatroom', related_name='chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
